// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOuAbw0qOaU3qLsoDcGN1S8NWnOuPgZ28',
    appId: '1:281121728435:web:unknown',
    messagingSenderId: '281121728435',
    projectId: 'tim-tro-sinh-vien',
    authDomain: 'tim-tro-sinh-vien.firebaseapp.com',
    storageBucket: 'tim-tro-sinh-vien.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOuAbw0qOaU3qLsoDcGN1S8NWnOuPgZ28',
    appId: '1:281121728435:android:1dfd6146de9b7364344dc6',
    messagingSenderId: '281121728435',
    projectId: 'tim-tro-sinh-vien',
    storageBucket: 'tim-tro-sinh-vien.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOuAbw0qOaU3qLsoDcGN1S8NWnOuPgZ28',
    appId: '1:281121728435:ios:unknown',
    messagingSenderId: '281121728435',
    projectId: 'tim-tro-sinh-vien',
    storageBucket: 'tim-tro-sinh-vien.firebasestorage.app',
    iosBundleId: 'com.example.tim_tro_sinh_vien',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOuAbw0qOaU3qLsoDcGN1S8NWnOuPgZ28',
    appId: '1:281121728435:ios:unknown',
    messagingSenderId: '281121728435',
    projectId: 'tim-tro-sinh-vien',
    storageBucket: 'tim-tro-sinh-vien.firebasestorage.app',
    iosBundleId: 'com.example.tim_tro_sinh_vien',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOuAbw0qOaU3qLsoDcGN1S8NWnOuPgZ28',
    appId: '1:281121728435:web:unknown',
    messagingSenderId: '281121728435',
    projectId: 'tim-tro-sinh-vien',
    authDomain: 'tim-tro-sinh-vien.firebaseapp.com',
    storageBucket: 'tim-tro-sinh-vien.firebasestorage.app',
  );
}
